import type { BeamType, LoadType } from "@/lib/reliability";

export type CapabilityLevel = "exact" | "approximate" | "envelope" | "planned";

export interface BeamCapabilityCell {
  level: CapabilityLevel;
  note: string;
}

export interface BeamCapabilityRow {
  beamType: BeamType;
  label: string;
  loads: Partial<Record<LoadType, BeamCapabilityCell>>;
}

export interface LoadCombinationPreset {
  id: string;
  standard: "LRFD" | "ASD" | "Service";
  name: string;
  expression: string;
  factors: Record<string, number>;
  useCase: string;
}

export const beamTypeLabels: Record<BeamType, string> = {
  "simply-supported": "Simply supported",
  cantilever: "Cantilever",
  "fixed-fixed": "Fixed-fixed",
  "propped-cantilever": "Propped cantilever",
  overhanging: "Overhanging",
  continuous: "Continuous 2-span",
  "multi-span": "Arbitrary multi-span",
  gerber: "Gerber/internal hinge",
  "elastic-foundation": "Elastic foundation",
  "spring-supported": "Spring-supported",
  settlement: "Support settlement beam",
  tapered: "Tapered/non-prismatic",
  "beam-column": "Beam-column",
  composite: "Composite beam",
};

export const loadTypeLabels: Record<LoadType, string> = {
  udl: "UDL",
  concentrated: "Point",
  triangular: "Triangular",
  moving: "Moving point",
  "partial-udl": "Partial UDL",
  trapezoidal: "Trapezoidal",
  moment: "Applied moment",
  parabolic: "Parabolic",
  parametric: "Parametric",
  "axle-train": "Axle train",
  "support-settlement": "Settlement",
  "thermal-gradient": "Thermal",
  prestress: "Prestress",
  patch: "Patch",
  torsional: "Torsion",
  "snow-drift": "Snow drift",
  hydrostatic: "Hydrostatic",
  "construction-stage": "Stage",
  "harmonic-equivalent": "Harmonic eq.",
};

const exact = (note: string): BeamCapabilityCell => ({ level: "exact", note });
const approximate = (note: string): BeamCapabilityCell => ({ level: "approximate", note });
const envelope = (note: string): BeamCapabilityCell => ({ level: "envelope", note });
const planned = (note: string): BeamCapabilityCell => ({ level: "planned", note });

export const beamCapabilityMatrix: BeamCapabilityRow[] = [
  {
    beamType: "simply-supported",
    label: beamTypeLabels["simply-supported"],
    loads: {
      udl: exact("Closed-form moment, shear, and deflection."),
      concentrated: exact("Arbitrary point position with influence line support."),
      triangular: exact("Full-span triangular idealization."),
      moving: envelope("Moving point load envelope is generated by sweeping positions."),
      "partial-udl": approximate("Resultant-based closed form with diagram integration."),
      trapezoidal: approximate("Equivalent resultant with linear load diagram."),
      moment: approximate("Applied couple response included; best for screening."),
      parabolic: approximate("Full-span symmetric parabolic load model."),
      parametric: planned("UI exposes parametric intent; numerical integration should be expanded."),
    },
  },
  {
    beamType: "cantilever",
    label: beamTypeLabels.cantilever,
    loads: {
      udl: exact("Classic cantilever UDL closed form."),
      concentrated: exact("Arbitrary point load from the fixed end."),
      triangular: exact("Full-span triangular idealization."),
      moving: envelope("Moving point load sweep for response envelopes."),
      "partial-udl": approximate("Partial distributed load reduced through resultant placement."),
      trapezoidal: approximate("Linear varying load reduced by resultant."),
      moment: approximate("Applied couple response included."),
      parabolic: approximate("Parabolic load idealized over span."),
      parametric: planned("Numerical function integration is a future solver target."),
    },
  },
  {
    beamType: "fixed-fixed",
    label: beamTypeLabels["fixed-fixed"],
    loads: {
      udl: exact("Fixed-end moments and reduced deflection included."),
      concentrated: approximate("Fixed-end point load approximation."),
      triangular: approximate("Equivalent fixed-end triangular load."),
      moving: envelope("Envelope sweep uses fixed-fixed diagram response."),
      "partial-udl": approximate("Partial UDL screening model."),
      trapezoidal: approximate("Linear load screening model."),
      moment: approximate("Applied couple screening model."),
      parabolic: approximate("Parabolic load screening model."),
      parametric: planned("General fixed-end numerical integration not yet implemented."),
    },
  },
  {
    beamType: "propped-cantilever",
    label: beamTypeLabels["propped-cantilever"],
    loads: {
      udl: exact("Propped cantilever UDL approximation with support moment."),
      concentrated: approximate("Point load support compatibility is simplified."),
      triangular: approximate("Resultant-based compatibility approximation."),
      moving: envelope("Moving point envelope generated from simplified response."),
      "partial-udl": approximate("Partial load screening model."),
      trapezoidal: approximate("Linear load screening model."),
      moment: approximate("Applied moment screening model."),
      parabolic: approximate("Parabolic load screening model."),
      parametric: planned("General compatibility solver is a future target."),
    },
  },
  {
    beamType: "overhanging",
    label: beamTypeLabels.overhanging,
    loads: {
      udl: approximate("Overhang response uses fixed support placement assumptions."),
      concentrated: approximate("Point load is idealized near overhang control case."),
      triangular: approximate("Resultant-based screening model."),
      moving: envelope("Moving point sweep available for envelopes."),
      "partial-udl": approximate("Partial UDL screening model."),
      trapezoidal: approximate("Linear load screening model."),
      moment: approximate("Applied couple screening model."),
      parabolic: approximate("Parabolic load screening model."),
      parametric: planned("General overhang integration is a future target."),
    },
  },
  {
    beamType: "continuous",
    label: beamTypeLabels.continuous,
    loads: {
      udl: approximate("Two-span continuous beam with simplified negative moment factors."),
      concentrated: approximate("Point load uses simplified continuous-beam factors."),
      triangular: approximate("Resultant-based continuous-beam screening."),
      moving: envelope("Envelope sweep available but not a full influence-surface solver."),
      "partial-udl": approximate("Partial UDL screening model."),
      trapezoidal: approximate("Linear load screening model."),
      moment: approximate("Applied couple screening model."),
      parabolic: approximate("Parabolic load screening model."),
      parametric: planned("Arbitrary multi-span solver is a future target."),
    },
  },
  {
    beamType: "multi-span",
    label: beamTypeLabels["multi-span"],
    loads: {
      udl: approximate("Routed through the continuous two-span screening model while arbitrary span stiffness is planned."),
      concentrated: approximate("Point loads use the continuous-beam screening path."),
      moving: envelope("Moving loads are swept through the continuous-beam envelope approximation."),
      "axle-train": planned("Needs influence-surface/axle-train solver for exact envelopes."),
      parametric: planned("General multi-span numerical integration is planned."),
    },
  },
  {
    beamType: "gerber",
    label: beamTypeLabels.gerber,
    loads: {
      udl: approximate("Screened as hinged simple-span segments."),
      concentrated: approximate("Internal hinge effects are represented by a simple-span equivalent."),
      moving: envelope("Moving point loads are swept over the equivalent span."),
      "axle-train": planned("Axle train across internal hinges is a priority future solver."),
      "support-settlement": planned("Hinge release and settlement compatibility need a dedicated solver."),
    },
  },
  {
    beamType: "elastic-foundation",
    label: beamTypeLabels["elastic-foundation"],
    loads: {
      udl: approximate("Currently screened through an equivalent simply supported beam."),
      concentrated: approximate("Point load response does not yet solve EI y'''' + k_s y = q(x)."),
      patch: approximate("Patch load is reduced to a partial distributed load."),
      hydrostatic: approximate("Pressure load is reduced to triangular demand."),
      parametric: planned("Full elastic-foundation numerical solver is planned."),
    },
  },
  {
    beamType: "spring-supported",
    label: beamTypeLabels["spring-supported"],
    loads: {
      udl: approximate("Routed through a simplified continuous support model."),
      concentrated: approximate("Spring stiffness compatibility is not yet exact."),
      "support-settlement": planned("Spring support displacement compatibility is planned."),
      moving: envelope("Moving load envelope uses the simplified support model."),
    },
  },
  {
    beamType: "settlement",
    label: beamTypeLabels.settlement,
    loads: {
      "support-settlement": approximate("Settlement is represented as an equivalent imposed moment."),
      udl: approximate("Uses propped-cantilever screening behavior."),
      "thermal-gradient": planned("Thermal plus settlement interaction is planned."),
    },
  },
  {
    beamType: "tapered",
    label: beamTypeLabels.tapered,
    loads: {
      udl: approximate("Uses equivalent prismatic stiffness until I(x) integration is added."),
      concentrated: approximate("Equivalent prismatic section screening."),
      moving: envelope("Envelope uses equivalent prismatic stiffness."),
      parametric: planned("Variable I(x) numerical integration is planned."),
    },
  },
  {
    beamType: "beam-column",
    label: beamTypeLabels["beam-column"],
    loads: {
      udl: approximate("Bending response is solved; P-delta amplification is a planned exact extension."),
      concentrated: approximate("Point load bending with beam-column caveat."),
      "harmonic-equivalent": approximate("Static-equivalent lateral demand for vibration screening."),
      "construction-stage": approximate("Construction stage load is factored as an equivalent UDL."),
    },
  },
  {
    beamType: "composite",
    label: beamTypeLabels.composite,
    loads: {
      udl: approximate("Uses transformed-section-style screening through the selected section properties."),
      concentrated: approximate("Equivalent section screening."),
      "construction-stage": approximate("Stage load is included as a UDL factor; staged composite action is planned."),
      prestress: approximate("Prestress is represented as equivalent uplift."),
    },
  },
];

export const loadCombinationPresets: LoadCombinationPreset[] = [
  {
    id: "lrfd-strength-gravity",
    standard: "LRFD",
    name: "Strength gravity",
    expression: "1.2D + 1.6L + 0.5S",
    factors: { D: 1.2, L: 1.6, S: 0.5 },
    useCase: "Common strength check where live load governs.",
  },
  {
    id: "lrfd-wind",
    standard: "LRFD",
    name: "Wind strength",
    expression: "1.2D + 1.0W + 1.0L + 0.5S",
    factors: { D: 1.2, W: 1.0, L: 1.0, S: 0.5 },
    useCase: "Member strength with wind present.",
  },
  {
    id: "lrfd-seismic",
    standard: "LRFD",
    name: "Seismic strength",
    expression: "1.2D + 1.0E + 1.0L + 0.2S",
    factors: { D: 1.2, E: 1.0, L: 1.0, S: 0.2 },
    useCase: "Seismic strength screening.",
  },
  {
    id: "asd-service",
    standard: "ASD",
    name: "Service gravity",
    expression: "D + L",
    factors: { D: 1.0, L: 1.0 },
    useCase: "Serviceability deflection and stress checks.",
  },
  {
    id: "service-deflection",
    standard: "Service",
    name: "Deflection service",
    expression: "D + 0.5L",
    factors: { D: 1.0, L: 0.5 },
    useCase: "Long-term or sustained serviceability screening.",
  },
];

export function getCapability(beamType: BeamType, loadType: LoadType): BeamCapabilityCell {
  return beamCapabilityMatrix.find((row) => row.beamType === beamType)?.loads[loadType] ?? planned("Combination is not currently documented.");
}
